apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: isekai
resources:
  - namespace.yaml
  - backend.yaml
  - planner.yaml
  - sandbox.yaml
  - frontend.yaml
  - networkpolicies.yaml
